# Expose the monitoring endpoints to the web
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Show full details in health check (great for dev/ops debugging)
management.endpoint.health.show-details=always